export type ScopeType = "READ" | "CREATE" | "UPDATE" | "DELETE" | "ALL" | "FULL";

export interface ZohoScope {
  id: string;
  scope: string;
  type: ScopeType;
  description: string;
  useCase: string;
}

export interface ZohoProduct {
  id: string;
  name: string;
  icon: string;
  color: string;
  description: string;
  scopes: ZohoScope[];
}

export const ZOHO_DOMAINS = [
  { label: "India (.in)", value: "https://accounts.zoho.in", region: "IN" },
  { label: "US (.com)", value: "https://accounts.zoho.com", region: "US" },
  { label: "Europe (.eu)", value: "https://accounts.zoho.eu", region: "EU" },
  { label: "Australia (.com.au)", value: "https://accounts.zoho.com.au", region: "AU" },
  { label: "Japan (.jp)", value: "https://accounts.zoho.jp", region: "JP" },
  { label: "Canada (.ca)", value: "https://accounts.zohocloud.ca", region: "CA" },
  { label: "Saudi Arabia (.sa)", value: "https://accounts.zoho.sa", region: "SA" },
];

export const SCOPE_TYPE_COLORS: Record<ScopeType, string> = {
  READ: "bg-blue-500/20 text-blue-300 border-blue-500/30",
  CREATE: "bg-green-500/20 text-green-300 border-green-500/30",
  UPDATE: "bg-yellow-500/20 text-yellow-300 border-yellow-500/30",
  DELETE: "bg-red-500/20 text-red-300 border-red-500/30",
  ALL: "bg-purple-500/20 text-purple-300 border-purple-500/30",
  FULL: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
};

export const ZOHO_PRODUCTS: ZohoProduct[] = [
  {
    id: "books",
    name: "Zoho Books",
    icon: "BookOpen",
    color: "text-green-400",
    description: "Online accounting software for managing finances, invoicing, and banking.",
    scopes: [
      { id: "books-1", scope: "ZohoBooks.fullaccess.all", type: "FULL", description: "Full access to Zoho Books", useCase: "Complete read/write access to all Books modules including invoices, bills, banking, and reports. Use when your integration needs unrestricted access." },
      { id: "books-2", scope: "ZohoBooks.invoices.ALL", type: "ALL", description: "Full access to invoices", useCase: "Create, read, update, delete invoices. Use for billing automation, invoice generation from CRM deals." },
      { id: "books-3", scope: "ZohoBooks.invoices.READ", type: "READ", description: "Read invoices", useCase: "Fetch invoice data for reporting dashboards, customer portals, or payment status tracking." },
      { id: "books-4", scope: "ZohoBooks.invoices.CREATE", type: "CREATE", description: "Create invoices", useCase: "Auto-generate invoices from project milestones, subscription renewals, or sales orders." },
      { id: "books-5", scope: "ZohoBooks.invoices.UPDATE", type: "UPDATE", description: "Update invoices", useCase: "Modify invoice line items, apply discounts, or update payment terms." },
      { id: "books-6", scope: "ZohoBooks.invoices.DELETE", type: "DELETE", description: "Delete invoices", useCase: "Remove draft or erroneous invoices. Use cautiously in production." },
      { id: "books-7", scope: "ZohoBooks.contacts.ALL", type: "ALL", description: "Full access to contacts", useCase: "Manage customer and vendor contacts. Sync with CRM or external address books." },
      { id: "books-8", scope: "ZohoBooks.contacts.READ", type: "READ", description: "Read contacts", useCase: "Fetch customer/vendor details for display in portals or reporting." },
      { id: "books-9", scope: "ZohoBooks.contacts.CREATE", type: "CREATE", description: "Create contacts", useCase: "Add new customers/vendors from signup forms, CRM, or import tools." },
      { id: "books-10", scope: "ZohoBooks.estimates.ALL", type: "ALL", description: "Full access to estimates", useCase: "Create and manage quotes/estimates. Convert to invoices or sales orders." },
      { id: "books-11", scope: "ZohoBooks.estimates.READ", type: "READ", description: "Read estimates", useCase: "Display estimate details in customer-facing portals or CRM." },
      { id: "books-12", scope: "ZohoBooks.expenses.ALL", type: "ALL", description: "Full access to expenses", useCase: "Track and manage business expenses, receipt uploads, and categorization." },
      { id: "books-13", scope: "ZohoBooks.expenses.READ", type: "READ", description: "Read expenses", useCase: "Pull expense data for financial reports or tax preparation." },
      { id: "books-14", scope: "ZohoBooks.bills.ALL", type: "ALL", description: "Full access to bills", useCase: "Manage vendor bills, schedule payments, and track due dates." },
      { id: "books-15", scope: "ZohoBooks.bills.READ", type: "READ", description: "Read bills", useCase: "View outstanding bills for cash flow forecasting." },
      { id: "books-16", scope: "ZohoBooks.banking.ALL", type: "ALL", description: "Full access to banking", useCase: "Bank reconciliation, transaction categorization, and bank feed management." },
      { id: "books-17", scope: "ZohoBooks.banking.READ", type: "READ", description: "Read banking data", useCase: "Fetch bank transactions for reconciliation reports." },
      { id: "books-18", scope: "ZohoBooks.accountants.ALL", type: "ALL", description: "Full access to chart of accounts", useCase: "Manage GL accounts, journal entries, and manual transactions." },
      { id: "books-19", scope: "ZohoBooks.settings.ALL", type: "ALL", description: "Full access to settings", useCase: "Configure taxes, currencies, payment gateways, templates, and organization settings." },
      { id: "books-20", scope: "ZohoBooks.settings.READ", type: "READ", description: "Read settings", useCase: "Fetch tax rates, currency list, and org details for form dropdowns." },
      { id: "books-21", scope: "ZohoBooks.purchaseorders.ALL", type: "ALL", description: "Full access to purchase orders", useCase: "Create and manage purchase orders to vendors." },
      { id: "books-22", scope: "ZohoBooks.salesorders.ALL", type: "ALL", description: "Full access to sales orders", useCase: "Manage sales orders before converting to invoices." },
      { id: "books-23", scope: "ZohoBooks.creditnotes.ALL", type: "ALL", description: "Full access to credit notes", useCase: "Issue and manage credit notes for refunds and adjustments." },
      { id: "books-24", scope: "ZohoBooks.creditnotes.READ", type: "READ", description: "Read credit notes", useCase: "Track issued credit notes for financial reporting." },
      { id: "books-25", scope: "ZohoBooks.customerpayments.ALL", type: "ALL", description: "Full access to customer payments", useCase: "Record and manage payments received from customers." },
      { id: "books-26", scope: "ZohoBooks.customerpayments.READ", type: "READ", description: "Read customer payments", useCase: "View payment history and outstanding balances." },
      { id: "books-27", scope: "ZohoBooks.vendorpayments.ALL", type: "ALL", description: "Full access to vendor payments", useCase: "Record and manage payments made to vendors." },
      { id: "books-28", scope: "ZohoBooks.projects.ALL", type: "ALL", description: "Full access to projects", useCase: "Manage projects, tasks, and time entries for project billing." },
      { id: "books-29", scope: "ZohoBooks.items.ALL", type: "ALL", description: "Full access to items", useCase: "Manage product/service catalog for invoicing." },
      { id: "books-30", scope: "ZohoBooks.items.READ", type: "READ", description: "Read items", useCase: "Fetch product catalog for dropdowns and price lists." },
    ],
  },
  {
    id: "cliq",
    name: "Zoho Cliq",
    icon: "MessageSquare",
    color: "text-yellow-400",
    description: "Team communication and collaboration platform with channels, bots, and integrations.",
    scopes: [
      { id: "cliq-1", scope: "ZohoCliq.Webhooks.CREATE", type: "CREATE", description: "Create incoming webhooks", useCase: "Set up webhooks to post automated messages to Cliq channels from CI/CD, monitoring, or CRM events." },
      { id: "cliq-2", scope: "ZohoCliq.Webhooks.READ", type: "READ", description: "Read webhooks", useCase: "List existing webhook configurations and their target channels." },
      { id: "cliq-3", scope: "ZohoCliq.Webhooks.UPDATE", type: "UPDATE", description: "Update webhooks", useCase: "Modify webhook URLs, names, or channel targets." },
      { id: "cliq-4", scope: "ZohoCliq.Webhooks.DELETE", type: "DELETE", description: "Delete webhooks", useCase: "Remove unused or decommissioned webhook integrations." },
      { id: "cliq-5", scope: "ZohoCliq.Channels.ALL", type: "ALL", description: "Full access to channels", useCase: "Create, read, update, and delete channels. Manage membership and channel settings." },
      { id: "cliq-6", scope: "ZohoCliq.Channels.READ", type: "READ", description: "Read channels", useCase: "List channels and their details for integration channel-picker UIs." },
      { id: "cliq-7", scope: "ZohoCliq.Channels.CREATE", type: "CREATE", description: "Create channels", useCase: "Auto-create channels for new projects, incidents, or deal rooms." },
      { id: "cliq-8", scope: "ZohoCliq.Channels.UPDATE", type: "UPDATE", description: "Update channels", useCase: "Rename channels, update descriptions, or modify settings." },
      { id: "cliq-9", scope: "ZohoCliq.Channels.DELETE", type: "DELETE", description: "Delete channels", useCase: "Archive or remove channels for completed projects." },
      { id: "cliq-10", scope: "ZohoCliq.ChatMessages.ALL", type: "ALL", description: "Full access to messages", useCase: "Read and send messages in chats and channels. Full chat automation." },
      { id: "cliq-11", scope: "ZohoCliq.ChatMessages.READ", type: "READ", description: "Read chat messages", useCase: "Fetch message history for compliance, audit, or search functionality." },
      { id: "cliq-12", scope: "ZohoCliq.ChatMessages.CREATE", type: "CREATE", description: "Send chat messages", useCase: "Post notifications, alerts, or bot responses to channels and DMs." },
      { id: "cliq-13", scope: "ZohoCliq.ChatMessages.UPDATE", type: "UPDATE", description: "Update messages", useCase: "Edit previously sent bot messages to update status or content." },
      { id: "cliq-14", scope: "ZohoCliq.ChatMessages.DELETE", type: "DELETE", description: "Delete messages", useCase: "Remove sensitive or erroneous messages posted by bots." },
      { id: "cliq-15", scope: "ZohoCliq.Buddies.READ", type: "READ", description: "Read buddy list", useCase: "List organization users for @mentions, DM targets, or user pickers." },
      { id: "cliq-16", scope: "ZohoCliq.Buddies.ALL", type: "ALL", description: "Full access to buddies", useCase: "Manage buddy/contact lists and user presence information." },
      { id: "cliq-17", scope: "ZohoCliq.Storages.ALL", type: "ALL", description: "Full access to storage", useCase: "Upload and manage files shared in Cliq chats and channels." },
      { id: "cliq-18", scope: "ZohoCliq.Storages.READ", type: "READ", description: "Read storage", useCase: "Download shared files and attachments from Cliq conversations." },
      { id: "cliq-19", scope: "ZohoCliq.Bots.ALL", type: "ALL", description: "Full access to bots", useCase: "Create, configure, and manage Cliq bots and their commands." },
      { id: "cliq-20", scope: "ZohoCliq.Bots.READ", type: "READ", description: "Read bots", useCase: "List available bots and their configurations." },
    ],
  },
  {
    id: "analytics",
    name: "Zoho Analytics",
    icon: "BarChart3",
    color: "text-purple-400",
    description: "Business intelligence and analytics platform for creating reports, dashboards, and data visualizations.",
    scopes: [
      { id: "analytics-1", scope: "ZohoAnalytics.fullaccess.all", type: "FULL", description: "Full access to Zoho Analytics", useCase: "Complete access to all workspaces, tables, reports, dashboards, and sharing. Use for admin-level integrations." },
      { id: "analytics-2", scope: "ZohoAnalytics.data.all", type: "ALL", description: "Full access to data operations", useCase: "Import, export, add, update, and delete data in tables. Core scope for ETL pipelines." },
      { id: "analytics-3", scope: "ZohoAnalytics.data.read", type: "READ", description: "Read analytics data", useCase: "Fetch report data and table records for external dashboards or data exports." },
      { id: "analytics-4", scope: "ZohoAnalytics.data.create", type: "CREATE", description: "Create/import data", useCase: "Push data from CRM, databases, or APIs into Analytics tables for reporting." },
      { id: "analytics-5", scope: "ZohoAnalytics.data.update", type: "UPDATE", description: "Update existing data", useCase: "Sync updated records from source systems. Useful for incremental data loads." },
      { id: "analytics-6", scope: "ZohoAnalytics.data.delete", type: "DELETE", description: "Delete data", useCase: "Remove outdated records or truncate tables before full re-import." },
      { id: "analytics-7", scope: "ZohoAnalytics.metadata.read", type: "READ", description: "Read workspace metadata", useCase: "List workspaces, tables, columns, and report definitions. Build dynamic UIs based on schema." },
      { id: "analytics-8", scope: "ZohoAnalytics.metadata.create", type: "CREATE", description: "Create metadata objects", useCase: "Create new workspaces, tables, columns, and reports programmatically." },
      { id: "analytics-9", scope: "ZohoAnalytics.metadata.update", type: "UPDATE", description: "Update metadata", useCase: "Modify table schema, rename columns, change data types, or update report configurations." },
      { id: "analytics-10", scope: "ZohoAnalytics.metadata.delete", type: "DELETE", description: "Delete metadata", useCase: "Remove unused tables, reports, or entire workspaces during cleanup." },
      { id: "analytics-11", scope: "ZohoAnalytics.share.read", type: "READ", description: "Read sharing settings", useCase: "Audit who has access to workspaces, reports, and dashboards." },
      { id: "analytics-12", scope: "ZohoAnalytics.share.create", type: "CREATE", description: "Share resources", useCase: "Grant access to reports and dashboards to team members or external users." },
      { id: "analytics-13", scope: "ZohoAnalytics.share.update", type: "UPDATE", description: "Update sharing", useCase: "Modify access levels or permissions on shared resources." },
      { id: "analytics-14", scope: "ZohoAnalytics.share.delete", type: "DELETE", description: "Remove sharing", useCase: "Revoke access from users who no longer need it." },
      { id: "analytics-15", scope: "ZohoAnalytics.usermanagement.read", type: "READ", description: "Read user info", useCase: "List workspace users, their roles, and access levels for admin dashboards." },
      { id: "analytics-16", scope: "ZohoAnalytics.usermanagement.create", type: "CREATE", description: "Add users", useCase: "Invite new users to Analytics workspaces programmatically." },
      { id: "analytics-17", scope: "ZohoAnalytics.embed.read", type: "READ", description: "Read embed URLs", useCase: "Generate embed URLs for embedding reports/dashboards in external applications." },
    ],
  },
  {
    id: "mail",
    name: "Zoho Mail",
    icon: "Mail",
    color: "text-blue-400",
    description: "Secure email hosting and management service for business communication.",
    scopes: [
      { id: "mail-1", scope: "ZohoMail.messages.ALL", type: "ALL", description: "Full access to email messages", useCase: "Read, send, reply, forward, and manage emails. Complete email automation." },
      { id: "mail-2", scope: "ZohoMail.messages.READ", type: "READ", description: "Read email messages", useCase: "Fetch emails for CRM integration, email analytics, or compliance archival." },
      { id: "mail-3", scope: "ZohoMail.messages.CREATE", type: "CREATE", description: "Send email messages", useCase: "Send transactional emails, notifications, or automated responses via API." },
      { id: "mail-4", scope: "ZohoMail.messages.UPDATE", type: "UPDATE", description: "Update email messages", useCase: "Mark emails as read/unread, star, flag, or move between folders." },
      { id: "mail-5", scope: "ZohoMail.messages.DELETE", type: "DELETE", description: "Delete email messages", useCase: "Trash or permanently delete emails for cleanup or compliance." },
      { id: "mail-6", scope: "ZohoMail.folders.ALL", type: "ALL", description: "Full access to mail folders", useCase: "Create, rename, delete, and manage email folders/labels." },
      { id: "mail-7", scope: "ZohoMail.folders.READ", type: "READ", description: "Read mail folders", useCase: "List folders, unread counts, and folder hierarchy." },
      { id: "mail-8", scope: "ZohoMail.folders.CREATE", type: "CREATE", description: "Create mail folders", useCase: "Auto-create folders for organizing emails by project or client." },
      { id: "mail-9", scope: "ZohoMail.accounts.ALL", type: "ALL", description: "Full access to mail accounts", useCase: "Manage email account settings, signatures, and forwarding rules." },
      { id: "mail-10", scope: "ZohoMail.accounts.READ", type: "READ", description: "Read mail accounts", useCase: "Get account info like storage usage, email aliases, and account status." },
      { id: "mail-11", scope: "ZohoMail.attachments.ALL", type: "ALL", description: "Full access to attachments", useCase: "Upload and download email attachments for processing or archival." },
      { id: "mail-12", scope: "ZohoMail.attachments.READ", type: "READ", description: "Read email attachments", useCase: "Download attachments for document processing, virus scanning, or backup." },
      { id: "mail-13", scope: "ZohoMail.tags.ALL", type: "ALL", description: "Full access to email tags", useCase: "Create, apply, and manage email tags/labels for organization." },
      { id: "mail-14", scope: "ZohoMail.tags.READ", type: "READ", description: "Read email tags", useCase: "List available tags for filtering and categorization UIs." },
      { id: "mail-15", scope: "ZohoMail.search.READ", type: "READ", description: "Search emails", useCase: "Full-text search across emails for e-discovery, compliance, or smart search features." },
      { id: "mail-16", scope: "ZohoMail.filters.ALL", type: "ALL", description: "Full access to mail filters", useCase: "Create and manage email filter rules for auto-sorting and forwarding." },
      { id: "mail-17", scope: "ZohoMail.filters.READ", type: "READ", description: "Read mail filters", useCase: "List active filter rules for audit or management UIs." },
    ],
  },
  {
    id: "salesiq",
    name: "Zoho SalesIQ",
    icon: "MessageCircle",
    color: "text-orange-400",
    description: "Live chat, visitor tracking, and customer engagement platform for websites.",
    scopes: [
      { id: "siq-1", scope: "SalesIQ.visitors.ALL", type: "ALL", description: "Full access to visitors", useCase: "Track, view, and manage website visitors. Core scope for visitor analytics." },
      { id: "siq-2", scope: "SalesIQ.visitors.READ", type: "READ", description: "Read visitor data", useCase: "Fetch visitor tracking data, page views, and visit history for analytics dashboards." },
      { id: "siq-3", scope: "SalesIQ.visitors.UPDATE", type: "UPDATE", description: "Update visitor data", useCase: "Add custom fields, notes, or tags to visitor profiles." },
      { id: "siq-4", scope: "SalesIQ.chats.ALL", type: "ALL", description: "Full access to chats", useCase: "Initiate, read, and manage live chat conversations with visitors." },
      { id: "siq-5", scope: "SalesIQ.chats.READ", type: "READ", description: "Read chat transcripts", useCase: "Fetch chat history for quality monitoring, training, or CRM sync." },
      { id: "siq-6", scope: "SalesIQ.chats.CREATE", type: "CREATE", description: "Initiate chats", useCase: "Proactively start chat with high-value visitors or trigger automated responses." },
      { id: "siq-7", scope: "SalesIQ.chats.UPDATE", type: "UPDATE", description: "Update chats", useCase: "Transfer chats, add internal notes, or update chat status." },
      { id: "siq-8", scope: "SalesIQ.chats.DELETE", type: "DELETE", description: "Delete chats", useCase: "Remove test chats or sensitive conversations." },
      { id: "siq-9", scope: "SalesIQ.operators.ALL", type: "ALL", description: "Full access to operators", useCase: "Manage chat operators/agents, their availability, and routing rules." },
      { id: "siq-10", scope: "SalesIQ.operators.READ", type: "READ", description: "Read operators", useCase: "List available agents and their online status for routing decisions." },
      { id: "siq-11", scope: "SalesIQ.departments.ALL", type: "ALL", description: "Full access to departments", useCase: "Create and manage departments for chat routing and organization." },
      { id: "siq-12", scope: "SalesIQ.departments.READ", type: "READ", description: "Read departments", useCase: "List departments for chat widget department picker." },
      { id: "siq-13", scope: "SalesIQ.chatbots.ALL", type: "ALL", description: "Full access to chatbots", useCase: "Create, configure, and manage AI chatbots and their conversation flows." },
      { id: "siq-14", scope: "SalesIQ.chatbots.READ", type: "READ", description: "Read chatbot config", useCase: "Fetch chatbot settings and performance metrics." },
      { id: "siq-15", scope: "SalesIQ.portals.ALL", type: "ALL", description: "Full access to portals", useCase: "Manage SalesIQ portals (website connections) and their embed settings." },
      { id: "siq-16", scope: "SalesIQ.portals.READ", type: "READ", description: "Read portals", useCase: "List connected websites and their tracking configurations." },
      { id: "siq-17", scope: "SalesIQ.feedback.ALL", type: "ALL", description: "Full access to feedback", useCase: "Manage post-chat feedback collection and ratings." },
      { id: "siq-18", scope: "SalesIQ.feedback.READ", type: "READ", description: "Read feedback", useCase: "Fetch customer satisfaction ratings for quality reports." },
      { id: "siq-19", scope: "SalesIQ.settings.ALL", type: "ALL", description: "Full access to settings", useCase: "Configure SalesIQ global settings, triggers, and automation rules." },
      { id: "siq-20", scope: "SalesIQ.settings.READ", type: "READ", description: "Read settings", useCase: "Fetch current configuration for audit or backup purposes." },
    ],
  },
  {
    id: "crm",
    name: "Zoho CRM",
    icon: "Users",
    color: "text-red-400",
    description: "Customer relationship management platform for sales, marketing, and support.",
    scopes: [
      { id: "crm-1", scope: "ZohoCRM.modules.ALL", type: "ALL", description: "Full access to all CRM modules", useCase: "Complete read/write access to Leads, Contacts, Deals, Accounts, and all custom modules." },
      { id: "crm-2", scope: "ZohoCRM.modules.READ", type: "READ", description: "Read all CRM modules", useCase: "Read-only access to all module records for reporting, dashboards, and data sync." },
      { id: "crm-3", scope: "ZohoCRM.modules.CREATE", type: "CREATE", description: "Create records in CRM", useCase: "Create new Leads, Contacts, or Deals from web forms, imports, or integrations." },
      { id: "crm-4", scope: "ZohoCRM.modules.UPDATE", type: "UPDATE", description: "Update CRM records", useCase: "Update existing records like changing deal stages, contact details, or lead status." },
      { id: "crm-5", scope: "ZohoCRM.modules.DELETE", type: "DELETE", description: "Delete CRM records", useCase: "Remove duplicate or outdated records. Use with caution in production." },
      { id: "crm-6", scope: "ZohoCRM.settings.ALL", type: "ALL", description: "Full access to settings", useCase: "Manage custom fields, layouts, modules, automation rules, and org settings." },
      { id: "crm-7", scope: "ZohoCRM.settings.READ", type: "READ", description: "Read CRM settings", useCase: "Fetch field metadata, layouts, picklist values for dynamic form rendering." },
      { id: "crm-8", scope: "ZohoCRM.users.ALL", type: "ALL", description: "Full access to users", useCase: "Manage user profiles, roles, territories, and permissions." },
      { id: "crm-9", scope: "ZohoCRM.users.READ", type: "READ", description: "Read CRM users", useCase: "List users for assignment dropdowns, audit trails, or org charts." },
      { id: "crm-10", scope: "ZohoCRM.org.ALL", type: "ALL", description: "Full access to organization", useCase: "Read and update org-level settings like fiscal year, currency, and time zone." },
      { id: "crm-11", scope: "ZohoCRM.org.READ", type: "READ", description: "Read organization details", useCase: "Fetch org info for multi-org integrations or branding." },
      { id: "crm-12", scope: "ZohoCRM.bulk.ALL", type: "ALL", description: "Full bulk operations", useCase: "Mass import/export records for data migration, bulk updates, or backup." },
      { id: "crm-13", scope: "ZohoCRM.bulk.READ", type: "READ", description: "Bulk read operations", useCase: "Export large datasets (100K+ records) for analytics or data warehouse sync." },
      { id: "crm-14", scope: "ZohoCRM.notifications.ALL", type: "ALL", description: "Manage notifications", useCase: "Subscribe to record change notifications via webhooks for real-time sync." },
      { id: "crm-15", scope: "ZohoCRM.coql.READ", type: "READ", description: "Execute COQL queries", useCase: "Run SQL-like queries on CRM data for complex filtering and ad-hoc reporting." },
      { id: "crm-16", scope: "ZohoCRM.files.READ", type: "READ", description: "Read file attachments", useCase: "Download attachments from records like notes, emails, and documents." },
      { id: "crm-17", scope: "ZohoCRM.files.CREATE", type: "CREATE", description: "Upload attachments", useCase: "Attach documents, images, or files to CRM records programmatically." },
    ],
  },
  {
    id: "desk",
    name: "Zoho Desk",
    icon: "Headphones",
    color: "text-cyan-400",
    description: "Help desk and customer support ticketing platform.",
    scopes: [
      { id: "desk-1", scope: "Desk.tickets.ALL", type: "ALL", description: "Full access to tickets", useCase: "Complete CRUD on support tickets for helpdesk automation and workflows." },
      { id: "desk-2", scope: "Desk.tickets.READ", type: "READ", description: "Read tickets", useCase: "Fetch ticket data for dashboards, customer portals, or SLA monitoring." },
      { id: "desk-3", scope: "Desk.tickets.CREATE", type: "CREATE", description: "Create tickets", useCase: "Auto-create tickets from emails, web forms, chat, or API calls." },
      { id: "desk-4", scope: "Desk.tickets.UPDATE", type: "UPDATE", description: "Update tickets", useCase: "Change ticket status, priority, assignee, or add comments." },
      { id: "desk-5", scope: "Desk.tickets.DELETE", type: "DELETE", description: "Delete tickets", useCase: "Remove spam or duplicate tickets from the system." },
      { id: "desk-6", scope: "Desk.contacts.ALL", type: "ALL", description: "Full access to contacts", useCase: "Manage customer contacts and their support history." },
      { id: "desk-7", scope: "Desk.contacts.READ", type: "READ", description: "Read contacts", useCase: "Look up customer info and ticket history when handling support." },
      { id: "desk-8", scope: "Desk.contacts.CREATE", type: "CREATE", description: "Create contacts", useCase: "Add new customers from CRM sync or external systems." },
      { id: "desk-9", scope: "Desk.articles.ALL", type: "ALL", description: "Full access to knowledge base", useCase: "Create and manage help center articles, categories, and sections." },
      { id: "desk-10", scope: "Desk.articles.READ", type: "READ", description: "Read knowledge base", useCase: "Fetch articles for AI chatbot responses or customer self-service portals." },
      { id: "desk-11", scope: "Desk.tasks.ALL", type: "ALL", description: "Full access to tasks", useCase: "Manage tasks associated with tickets for team assignment." },
      { id: "desk-12", scope: "Desk.settings.ALL", type: "ALL", description: "Full access to settings", useCase: "Configure departments, SLAs, automation rules, and business hours." },
      { id: "desk-13", scope: "Desk.basic.ALL", type: "ALL", description: "Basic Desk access", useCase: "Minimal access for lightweight integrations that need limited functionality." },
      { id: "desk-14", scope: "Desk.search.READ", type: "READ", description: "Search across Desk", useCase: "Full-text search on tickets, contacts, and articles." },
    ],
  },
  {
    id: "people",
    name: "Zoho People",
    icon: "UserCheck",
    color: "text-teal-400",
    description: "HR management platform for employee data, attendance, and leave management.",
    scopes: [
      { id: "people-1", scope: "ZohoPeople.forms.ALL", type: "ALL", description: "Full access to HR forms", useCase: "Read and write employee data across all HR forms and modules." },
      { id: "people-2", scope: "ZohoPeople.forms.READ", type: "READ", description: "Read HR forms", useCase: "Fetch employee details, leave balances, attendance, and org structure." },
      { id: "people-3", scope: "ZohoPeople.forms.CREATE", type: "CREATE", description: "Create form records", useCase: "Add new employees, submit leave requests, or log attendance entries." },
      { id: "people-4", scope: "ZohoPeople.forms.UPDATE", type: "UPDATE", description: "Update form records", useCase: "Update employee details, approve leave, or modify attendance." },
      { id: "people-5", scope: "ZohoPeople.forms.DELETE", type: "DELETE", description: "Delete form records", useCase: "Remove incorrect or duplicate HR entries." },
      { id: "people-6", scope: "ZohoPeople.attendance.ALL", type: "ALL", description: "Full access to attendance", useCase: "Track check-in/out, overtime, shifts, and attendance regularization." },
      { id: "people-7", scope: "ZohoPeople.attendance.READ", type: "READ", description: "Read attendance data", useCase: "Generate attendance reports, export for payroll processing." },
      { id: "people-8", scope: "ZohoPeople.leave.ALL", type: "ALL", description: "Full access to leave", useCase: "Manage leave types, balances, requests, and approvals." },
      { id: "people-9", scope: "ZohoPeople.leave.READ", type: "READ", description: "Read leave data", useCase: "Fetch leave balances and history for payroll or team calendars." },
      { id: "people-10", scope: "ZohoPeople.timetracker.ALL", type: "ALL", description: "Full access to time tracker", useCase: "Log and manage time entries for project billing and productivity tracking." },
    ],
  },
  {
    id: "projects",
    name: "Zoho Projects",
    icon: "FolderKanban",
    color: "text-indigo-400",
    description: "Project management and collaboration platform with tasks, milestones, and Gantt charts.",
    scopes: [
      { id: "proj-1", scope: "ZohoProjects.portals.ALL", type: "ALL", description: "Full access to portals", useCase: "Manage project portals and their settings." },
      { id: "proj-2", scope: "ZohoProjects.portals.READ", type: "READ", description: "Read portals", useCase: "List available portals and their configurations." },
      { id: "proj-3", scope: "ZohoProjects.projects.ALL", type: "ALL", description: "Full access to projects", useCase: "Create, read, update, and delete projects with full control." },
      { id: "proj-4", scope: "ZohoProjects.projects.READ", type: "READ", description: "Read projects", useCase: "Fetch project details, statuses, and team members for dashboards." },
      { id: "proj-5", scope: "ZohoProjects.projects.CREATE", type: "CREATE", description: "Create projects", useCase: "Auto-create projects from CRM deals, templates, or onboarding flows." },
      { id: "proj-6", scope: "ZohoProjects.tasks.ALL", type: "ALL", description: "Full access to tasks", useCase: "Complete task management: create, assign, track, and close tasks." },
      { id: "proj-7", scope: "ZohoProjects.tasks.READ", type: "READ", description: "Read tasks", useCase: "Fetch tasks for Gantt charts, workload reports, or Kanban boards." },
      { id: "proj-8", scope: "ZohoProjects.tasks.CREATE", type: "CREATE", description: "Create tasks", useCase: "Add tasks from external tools, automation, or recurring templates." },
      { id: "proj-9", scope: "ZohoProjects.tasks.UPDATE", type: "UPDATE", description: "Update tasks", useCase: "Mark tasks complete, update progress, change assignees, or reschedule." },
      { id: "proj-10", scope: "ZohoProjects.timesheets.ALL", type: "ALL", description: "Full access to timesheets", useCase: "Log time, approve timesheets, and generate billing reports." },
      { id: "proj-11", scope: "ZohoProjects.timesheets.READ", type: "READ", description: "Read timesheets", useCase: "Fetch time logs for invoicing, payroll, or productivity analytics." },
      { id: "proj-12", scope: "ZohoProjects.bugs.ALL", type: "ALL", description: "Full access to bug tracker", useCase: "Report, assign, and track bug resolution within projects." },
      { id: "proj-13", scope: "ZohoProjects.milestones.ALL", type: "ALL", description: "Full access to milestones", useCase: "Create and track project milestones and deliverables." },
      { id: "proj-14", scope: "ZohoProjects.documents.ALL", type: "ALL", description: "Full access to documents", useCase: "Upload and manage project files, wiki pages, and documents." },
    ],
  },
  {
    id: "inventory",
    name: "Zoho Inventory",
    icon: "Package",
    color: "text-amber-400",
    description: "Inventory and order management for tracking stock, orders, and warehouses.",
    scopes: [
      { id: "inv-1", scope: "ZohoInventory.fullaccess.all", type: "FULL", description: "Full access to Inventory", useCase: "Complete access to all Inventory modules for admin integrations." },
      { id: "inv-2", scope: "ZohoInventory.items.ALL", type: "ALL", description: "Full access to items", useCase: "Manage product catalog, pricing, stock levels, and variants." },
      { id: "inv-3", scope: "ZohoInventory.items.READ", type: "READ", description: "Read items", useCase: "Sync product data to ecommerce platforms or POS systems." },
      { id: "inv-4", scope: "ZohoInventory.items.CREATE", type: "CREATE", description: "Create items", useCase: "Add new products from supplier feeds or bulk imports." },
      { id: "inv-5", scope: "ZohoInventory.salesorders.ALL", type: "ALL", description: "Full access to sales orders", useCase: "Create and manage sales orders, fulfillment, and shipping." },
      { id: "inv-6", scope: "ZohoInventory.purchaseorders.ALL", type: "ALL", description: "Full access to purchase orders", useCase: "Create POs and manage vendor procurement workflows." },
      { id: "inv-7", scope: "ZohoInventory.invoices.ALL", type: "ALL", description: "Full access to invoices", useCase: "Generate and manage invoices from fulfilled sales orders." },
      { id: "inv-8", scope: "ZohoInventory.contacts.ALL", type: "ALL", description: "Full access to contacts", useCase: "Manage customer and vendor contact records." },
      { id: "inv-9", scope: "ZohoInventory.packages.ALL", type: "ALL", description: "Full access to packages", useCase: "Create shipment packages, print labels, and track delivery." },
      { id: "inv-10", scope: "ZohoInventory.warehouses.ALL", type: "ALL", description: "Full access to warehouses", useCase: "Manage warehouse locations, stock levels, and inter-warehouse transfers." },
      { id: "inv-11", scope: "ZohoInventory.settings.ALL", type: "ALL", description: "Full access to settings", useCase: "Configure taxes, currencies, shipping, and organization settings." },
    ],
  },
  {
    id: "creator",
    name: "Zoho Creator",
    icon: "Blocks",
    color: "text-pink-400",
    description: "Low-code application development platform for building custom business apps.",
    scopes: [
      { id: "creator-1", scope: "ZohoCreator.report.ALL", type: "ALL", description: "Full access to reports", useCase: "Read and manage report data in Creator apps." },
      { id: "creator-2", scope: "ZohoCreator.report.READ", type: "READ", description: "Read reports", useCase: "Fetch report data for external dashboards or integrations." },
      { id: "creator-3", scope: "ZohoCreator.form.ALL", type: "ALL", description: "Full access to forms", useCase: "Submit and manage form data in Creator applications." },
      { id: "creator-4", scope: "ZohoCreator.form.CREATE", type: "CREATE", description: "Submit form data", useCase: "Push data into Creator apps from external systems." },
      { id: "creator-5", scope: "ZohoCreator.meta.application.READ", type: "READ", description: "Read app metadata", useCase: "List applications, forms, and reports in a Creator account." },
      { id: "creator-6", scope: "ZohoCreator.meta.form.READ", type: "READ", description: "Read form metadata", useCase: "Get form field definitions for dynamic form rendering." },
      { id: "creator-7", scope: "ZohoCreator.dashboard.READ", type: "READ", description: "Read dashboards", useCase: "Embed Creator dashboards in external portals." },
      { id: "creator-8", scope: "ZohoCreator.bulk.ALL", type: "ALL", description: "Bulk operations", useCase: "Mass import/export data in Creator apps." },
    ],
  },
  {
    id: "sign",
    name: "Zoho Sign",
    icon: "PenTool",
    color: "text-sky-400",
    description: "Digital signature platform for signing and managing documents online.",
    scopes: [
      { id: "sign-1", scope: "ZohoSign.documents.ALL", type: "ALL", description: "Full access to documents", useCase: "Create, send, and manage documents for e-signature workflows." },
      { id: "sign-2", scope: "ZohoSign.documents.READ", type: "READ", description: "Read documents", useCase: "Track document signing status and download completed copies." },
      { id: "sign-3", scope: "ZohoSign.documents.CREATE", type: "CREATE", description: "Create documents", useCase: "Send documents for signature from CRM deals or HR onboarding." },
      { id: "sign-4", scope: "ZohoSign.templates.ALL", type: "ALL", description: "Full access to templates", useCase: "Manage reusable document templates for contracts and agreements." },
      { id: "sign-5", scope: "ZohoSign.templates.READ", type: "READ", description: "Read templates", useCase: "List available templates for document generation workflows." },
      { id: "sign-6", scope: "ZohoSign.account.ALL", type: "ALL", description: "Full access to account", useCase: "Manage Sign account settings, branding, and notifications." },
    ],
  },
  {
    id: "subscriptions",
    name: "Zoho Subscriptions",
    icon: "CreditCard",
    color: "text-emerald-400",
    description: "Subscription billing and recurring payment management platform.",
    scopes: [
      { id: "sub-1", scope: "ZohoSubscriptions.fullaccess.all", type: "FULL", description: "Full access to Subscriptions", useCase: "Complete access to manage all recurring billing operations." },
      { id: "sub-2", scope: "ZohoSubscriptions.customers.ALL", type: "ALL", description: "Full access to customers", useCase: "Manage subscriber accounts, payment methods, and billing info." },
      { id: "sub-3", scope: "ZohoSubscriptions.customers.READ", type: "READ", description: "Read customers", useCase: "Fetch customer subscription status for portals and dashboards." },
      { id: "sub-4", scope: "ZohoSubscriptions.subscriptions.ALL", type: "ALL", description: "Full access to subscriptions", useCase: "Create, modify, pause, resume, and cancel subscriptions." },
      { id: "sub-5", scope: "ZohoSubscriptions.subscriptions.READ", type: "READ", description: "Read subscriptions", useCase: "Track active subscriptions, renewal dates, and MRR." },
      { id: "sub-6", scope: "ZohoSubscriptions.invoices.ALL", type: "ALL", description: "Full access to invoices", useCase: "Manage recurring invoices and payment collection." },
      { id: "sub-7", scope: "ZohoSubscriptions.invoices.READ", type: "READ", description: "Read invoices", useCase: "Fetch invoice history for customer billing portals." },
      { id: "sub-8", scope: "ZohoSubscriptions.plans.ALL", type: "ALL", description: "Full access to plans", useCase: "Create and manage subscription plans, addons, and pricing tiers." },
      { id: "sub-9", scope: "ZohoSubscriptions.plans.READ", type: "READ", description: "Read plans", useCase: "Display available plans on pricing pages or plan selectors." },
    ],
  },
  {
    id: "recruit",
    name: "Zoho Recruit",
    icon: "Briefcase",
    color: "text-lime-400",
    description: "Applicant tracking and recruitment management system.",
    scopes: [
      { id: "recruit-1", scope: "ZohoRecruit.modules.ALL", type: "ALL", description: "Full access to modules", useCase: "Complete access to candidates, job openings, interviews, and assessments." },
      { id: "recruit-2", scope: "ZohoRecruit.modules.READ", type: "READ", description: "Read modules", useCase: "Fetch candidate and job data for career portals or ATS dashboards." },
      { id: "recruit-3", scope: "ZohoRecruit.modules.CREATE", type: "CREATE", description: "Create records", useCase: "Add candidates from job boards, referral programs, or resume parsing." },
      { id: "recruit-4", scope: "ZohoRecruit.modules.UPDATE", type: "UPDATE", description: "Update records", useCase: "Move candidates through hiring pipeline stages." },
      { id: "recruit-5", scope: "ZohoRecruit.settings.ALL", type: "ALL", description: "Full access to settings", useCase: "Configure custom fields, hiring stages, and workflow rules." },
      { id: "recruit-6", scope: "ZohoRecruit.settings.READ", type: "READ", description: "Read settings", useCase: "Fetch picklist values and field metadata for forms." },
    ],
  },
  {
    id: "campaigns",
    name: "Zoho Campaigns",
    icon: "Megaphone",
    color: "text-rose-400",
    description: "Email marketing automation platform for campaigns and subscriber management.",
    scopes: [
      { id: "camp-1", scope: "ZohoCampaigns.contact.ALL", type: "ALL", description: "Full access to contacts", useCase: "Manage mailing lists, subscribers, segments, and custom fields." },
      { id: "camp-2", scope: "ZohoCampaigns.contact.READ", type: "READ", description: "Read contacts", useCase: "Fetch subscriber lists and engagement data for analytics." },
      { id: "camp-3", scope: "ZohoCampaigns.contact.CREATE", type: "CREATE", description: "Create contacts", useCase: "Add subscribers from signup forms, CRM, or import tools." },
      { id: "camp-4", scope: "ZohoCampaigns.contact.UPDATE", type: "UPDATE", description: "Update contacts", useCase: "Update subscriber preferences, custom fields, or list membership." },
      { id: "camp-5", scope: "ZohoCampaigns.campaign.ALL", type: "ALL", description: "Full access to campaigns", useCase: "Create, schedule, send, and manage email campaigns." },
      { id: "camp-6", scope: "ZohoCampaigns.campaign.READ", type: "READ", description: "Read campaigns", useCase: "Fetch campaign performance metrics, stats, and schedules." },
      { id: "camp-7", scope: "ZohoCampaigns.reports.READ", type: "READ", description: "Read campaign reports", useCase: "Get open rates, click rates, bounce data, and unsubscribes." },
    ],
  },
];
